name: AutoDay

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '6 6 * * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          DAY_JSON: ${{ secrets.DAY_JSON }}
        run: |
          echo "" > output.log  # 清空或创建 output.log
          echo "$DAY_JSON" | jq -c '.[]' | while read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')
            cmd=$(echo "$server" | jq -r '.cmd')
            
            echo "Executing command on $ssh: $cmd" >> output.log  # 写入日志
            output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$username@$ssh" "$cmd" 2>&1)
            
            echo "Output from $ssh:" >> output.log  # 写入日志
            echo "$output" >> output.log
            
            sleep 1  # 等待5秒，增加延迟
          done
      
          cat output.log  # 在循环外部一次性打印
