name: AutoDay

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '7 7 * * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          DAY_JSON: ${{ secrets.DAY_JSON }}
        run: |
          echo "" > output.log  # 清空或创建 output.log
          echo "$DAY_JSON" | jq -c '.[]' | while read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')
            cmd=$(echo "$server" | jq -r '.cmd')
            
            echo "Processing server: $ssh" >> output.log  # Debug log

            {
              echo "Executing command on $ssh at $(date): $cmd" >> output.log
              output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$username@$ssh" "$cmd" 2>&1)
              echo "Output from $ssh:" >> output.log
              echo "$output" >> output.log
              if [[ $? -ne 0 ]]; then
                echo "Error executing command on $ssh" >> output.log
              fi
            } &
          done
          wait

          cat output.log
