name: AutoDay

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '6 6 * * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          DAY_JSON: ${{ secrets.DAY_JSON }}
        run: |
          echo "$DAY_JSON" | jq -c '.[]' | while IFS= read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')
            cmd=$(echo "$server" | jq -r '.cmd')
            
            echo "Executing command on $username@$ssh: $cmd"
            output=$(sshpass -p "$password" ssh -n -o StrictHostKeyChecking=no "$username@$ssh" "$cmd" 2>&1)
            echo "$output"
            
            sleep 2  # Wait 2 seconds for delay
          done
