name: SSH

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '7 5 */30 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "" > output.log  # Clear or create output.log
          echo "$SERVERS_JSON" | jq -c '.[]' | while read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')
            echo "Executing command on $ssh: $cmd" >> output.log  # 写入日志

            # 使用 sshpass 执行命令，并捕获输出
            output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$username@$ssh" "pwd" 2>&1)
      
            echo "Output from $ssh:" >> output.log  # Log output
            echo "$output" >> output.log
            
            sleep 2  # Wait 2 seconds for delay
          done
      
          cat output.log  # 在循环外部一次性打印
