name: SSH

on:
  push:
    branches:
      - main

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install jq and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y jq sshpass

      - name: Execute command on remote servers
        run: |
          echo "${{ secrets.SSH_JSON }}" | jq -c '.[]' | while IFS= read -r server; do
            username=$(echo $server | jq -r '.username')
            password=$(echo $server | jq -r '.password')
            ssh_host=$(echo $server | jq -r '.ssh')
            echo "Connecting to $ssh_host as $username"
            sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$username@$ssh_host" "pwd"
          done
