name: SSH

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '7 5 1 */2 *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq screen

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "$SERVERS_JSON" | jq -c '.[]' | while IFS= read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')

            echo "Starting a new screen session to execute command on $username@$ssh..."
            screen -dmS "ssh_session_$ssh" bash -c "
              output=\$(sshpass -p \"$password\" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR \"$username@$ssh\" \"pwd\" 2>&1);
              if [[ \$? -ne 0 ]]; then
                echo \"❌ Error executing command on $username@$ssh: \$output\" >> /tmp/ssh_errors.log;
              else
                echo \"✅ Successfully executed command on $username@$ssh: \$output\" >> /tmp/ssh_success.log;
              fi
            "

            echo "Waiting for 5 seconds before proceeding to the next server..."
            sleep 5
          done

          echo "All commands have been executed."
