name: SSH

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '7 5 1 */2 *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq screen

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "$SERVERS_JSON" | jq -c '.[]' | while IFS= read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')

            echo "Executing command on $username@$ssh..."
            screen -dmS ssh_session sshpass -p "$password" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR "$username@$ssh" "pwd; sleep 5; exit"

            # 输出命令结果
            output=$(screen -S ssh_session -X stuff "exit$(echo -ne '\015')")
            echo "$output"

            # 检查命令是否成功
            if [[ $? -ne 0 ]]; then
              echo "❌ Error executing command on $username@$ssh"
            else
              echo "✅ Successfully executed command on $username@$ssh"
            fi

            echo "Waiting for 5 seconds before proceeding to the next server..."
          done

          echo "All commands have been executed."
