name: SSH

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: '7 5 */30 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Execute command on remote servers
        env:
          SSH_JSON: ${{ secrets.SSH_JSON }}
        run: |
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')
            sshpass -p '$password' ssh -o StrictHostKeyChecking=no '$username@$ssh' 'pwd'
          done < <(jq -c '.[]' $SSH_JSON)

