name: SSH

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: '7 5 */30 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "$SERVERS_JSON" | jq -c '.[]' | while read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')
            echo "Connecting to $ssh as $username"
            if output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$username@$ssh" 'pwd'); then
              echo "Successfully connected to $ssh: $output" | tee /dev/stderr
            else
              echo "Failed to connect to $ssh" | tee /dev/stderr
            fi
          done
