name: SSH

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: '7 5 */30 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          # 解析 JSON 字符串并执行命令
          while IFS= read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')
  
            echo "Connecting to $hostname as $username"
            sshpass -p $password ssh -o StrictHostKeyChecking=no $username@$ssh 'pwd'
          done < <(echo $SERVERS_JSON | jq -c '.[]')

