name: SSH

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '7 5 1 */2 *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 sshpass 和 jq
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: 输出服务器配置
        id: output_servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "服务器配置内容："
          echo "$SERVERS_JSON" | jq .
          echo "servers=$SERVERS_JSON" >> $GITHUB_ENV

  run_commands:
    needs: execute-commands
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ${{ fromJson(env.servers) }}
    steps:
      - name: 执行远程服务器命令
        run: |
          username=$(echo "${{ matrix.server }}" | jq -r '.username')
          password=$(echo "${{ matrix.server }}" | jq -r '.password')
          ssh_host=$(echo "${{ matrix.server }}" | jq -r '.ssh')

          echo "正在在服务器 $ssh_host 上以用户 $username 执行命令..."
          output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR "$username@$ssh_host" "pwd" 2>&1)

          # 输出命令结果
          echo "$output"

          # 检查命令是否成功
          if [[ $? -ne 0 ]]; then
            echo "❌ 执行命令时出错：$username@$ssh_host"
          else
            echo "✅ 成功在 $username@$ssh_host 上执行命令"
          fi
