name: SSH

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '7 21 3 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq screen

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "$SERVERS_JSON" | jq -c '.[]' | while IFS= read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')

            echo "Starting screen session for $username@$ssh..."
            screen -dmS "ssh_session_$ssh" bash -c "echo 'Executing command on $username@$ssh...' && sshpass -p \"$password\" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR \"$username@$ssh\" 'pwd' > screen_log_$ssh.log 2>&1"

            # Wait for the command to finish and log output
            echo "Waiting for command to finish on $username@$ssh..."
            sleep 5  # Adjust this as necessary based on expected command duration

            # Output the log from the screen session
            echo "Log for $username@$ssh:"
            cat screen_log_$ssh.log || echo "❌ Failed to retrieve log for $username@$ssh"

            echo "✅ Successfully executed command on $username@$ssh"
            echo "Waiting for 5 seconds before proceeding to the next server..."
            sleep 5
          done

          echo "All commands have been executed."
