name: SSH

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '7 5 */30 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "$SERVERS_JSON" | jq -c '.[]' | while IFS= read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')

            echo "Executing command on $username@$ssh..."
            sshpass -p "$password" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR "$username@$ssh" "pwd" > output.log 2>&1 &
            pid=$!

            # Check if the command is running in the background
            if [[ $? -ne 0 ]]; then
              echo "❌ Error starting command on $username@$ssh"
            else
              echo "✅ Successfully started command on $username@$ssh (PID: $pid)"
            fi
            
            echo "Waiting for 5 seconds before proceeding to the next server..."
            sleep 5
          done

          # Wait for all background jobs to finish
          wait

          echo "All commands have been executed."
