name: SSH

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '7 5 */30 * *'

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass jq

      - name: Execute command on remote servers
        env:
          SERVERS_JSON: ${{ secrets.SSH_JSON }}
        run: |
          echo "$SERVERS_JSON" | jq -c '.[]' | while IFS= read -r server; do
            username=$(echo "$server" | jq -r '.username')
            password=$(echo "$server" | jq -r '.password')
            ssh=$(echo "$server" | jq -r '.ssh')
            
            echo "Executing command on $username@$ssh"
            output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no -o BatchMode=yes "$username@$ssh" "pwd" 2>&1)
            echo "$output"
            
            # Check for success or failure
            if [[ $? -ne 0 ]]; then
              echo "Error executing command on $username@$ssh"
            else
              echo "Successfully executed command on $username@$ssh"
            fi
            
            sleep 5  # Wait 5 seconds for delay
          done
